# Generated by Django 3.1 on 2021-05-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('machine', models.CharField(max_length=255)),
                ('duration', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('details', models.TextField(null=True)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engine_relation', to='environment.environment')),
            ],
            options={
                'verbose_name': 'engine',
                'verbose_name_plural': 'engines',
                'db_table': 'model_manager_engine',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('environment', 'name')},
            },
        ),
    ]
