# Generated by Django 3.1 on 2021-05-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='details',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='duration',
        ),
    ]
