# Generated by Django 3.1 on 2021-05-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudokey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pseudokey',
            options={'ordering': ['name'], 'verbose_name': 'key', 'verbose_name_plural': 'keys'},
        ),
    ]
