# Generated by Django 3.1 on 2021-05-19 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_config', '0002_modelconfig_hyperparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('trained_model', models.BinaryField(null=True)),
                ('config', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeltraining_relation', to='model_config.modelconfig')),
            ],
            options={
                'verbose_name': 'model training',
                'verbose_name_plural': 'model trainings',
                'db_table': 'model_manager_model_training',
                'ordering': ['-time'],
                'abstract': False,
                'unique_together': {('config', 'time')},
            },
        ),
    ]
