# Generated by Django 3.1 on 2021-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0001_initial'),
        ('model_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraining',
            name='sources',
            field=models.ManyToManyField(related_name='modeltraining_relations', to='data_source.DataSource'),
        ),
    ]
