# Generated by Django 3.1 on 2021-05-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        ('model_training', '0002_modeltraining_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraining',
            name='engine',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeltraining_relation', to='engine.engine'),
        ),
    ]
