# Generated by Django 3.1 on 2021-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0003_modeltraining_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraining',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='modeltraining',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modeltraining',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
