# Generated by Django 3.1 on 2021-05-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0004_auto_20210519_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltraining',
            options={'ordering': ['-time'], 'verbose_name': 'training', 'verbose_name_plural': 'trainings'},
        ),
    ]
