# Generated by Django 3.1 on 2021-05-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudokey', '0001_initial'),
        ('hyperparameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperparameter',
            name='key',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hyperparameter_relation', to='pseudokey.pseudokey'),
        ),
    ]
