# Generated by Django 3.1 on 2021-05-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_auto_20210519_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['name'], 'verbose_name': 'data source', 'verbose_name_plural': 'data sources'},
        ),
    ]
